version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: broccoli-asset-rev
    versions:
    - ">= 0"
  - dependency-name: ember-ajax
    versions:
    - ">= 0"
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: ember-cli-app-version
    versions:
    - ">= 0"
  - dependency-name: ember-cli-babel
    versions:
    - ">= 0"
  - dependency-name: ember-cli-dependency-checker
    versions:
    - ">= 0"
  - dependency-name: ember-cli-eslint
    versions:
    - ">= 0"
  - dependency-name: ember-cli-htmlbars
    versions:
    - ">= 0"
  - dependency-name: ember-cli-htmlbars-inline-precompile
    versions:
    - ">= 0"
  - dependency-name: ember-cli-inject-live-reload
    versions:
    - ">= 0"
  - dependency-name: ember-cli-sri
    versions:
    - ">= 0"
  - dependency-name: ember-cli-template-lint
    versions:
    - ">= 0"
  - dependency-name: ember-cli-uglify
    versions:
    - ">= 0"
  - dependency-name: ember-data
    versions:
    - ">= 0"
  - dependency-name: ember-export-application-global
    versions:
    - ">= 0"
  - dependency-name: "@ember/jquery"
    versions:
    - ">= 0"
  - dependency-name: ember-load-initializers
    versions:
    - ">= 0"
  - dependency-name: ember-maybe-import-regenerator
    versions:
    - ">= 0"
  - dependency-name: "@ember/optional-features"
    versions:
    - ">= 0"
  - dependency-name: ember-qunit
    versions:
    - ">= 0"
  - dependency-name: ember-resolver
    versions:
    - ">= 0"
  - dependency-name: ember-source
    versions:
    - ">= 0"
  - dependency-name: ember-welcome-page
    versions:
    - ">= 0"
  - dependency-name: eslint-plugin-ember
    versions:
    - ">= 0"
  - dependency-name: eslint-plugin-node
    versions:
    - ">= 0"
  - dependency-name: loader.js
    versions:
    - ">= 0"
  - dependency-name: qunit-dom
    versions:
    - ">= 0"
  - dependency-name: caniuse-db
    versions:
    - 1.0.30001218
  - dependency-name: validator
    versions:
    - 13.6.0
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.3
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.25.0
  - dependency-name: ilios-common
    versions:
    - 56.1.0
  - dependency-name: ember-template-lint
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: "@glimmer/component"
    versions:
    - 1.0.4
  - dependency-name: browserslist
    versions:
    - 4.16.3
