---
language: node_js
node_js: 8
sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1

install:
- yarn install --non-interactive

before_script: greenkeeper-lockfile-update

script:
- yarn lint:js
- yarn test

after_script: greenkeeper-lockfile-upload

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node_modules/.bin/ember deploy staging --activate
- test $TRAVIS_TAG && node_modules/.bin/ember deploy production --activate

